<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <!-- Project Information -->
    <groupId>com.example</groupId>
    <artifactId>mini-ticket-app</artifactId>

    <!-- Jenkins overrides this using -Drevision=1.0.${BUILD_NUMBER} -->
    <version>${revision}</version>

    <packaging>jar</packaging>


    <!-- Project Properties -->
    <properties>

        <!-- Default version when building outside Jenkins -->
        <revision>1.0.0</revision>

        <!-- Java -->
        <java.version>21</java.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>

        <!-- Spring Boot -->
        <spring-boot.version>3.3.5</spring-boot.version>

    </properties>


    <!-- Dependencies -->
    <dependencies>

        <!-- Spring Boot REST API -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>${spring-boot.version}</version>
        </dependency>


        <!-- Unit Testing -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>${spring-boot.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>


    <!-- Nexus Repository -->
    <distributionManagement>

        <repository>
            <id>nexus</id>
            <name>Nexus Releases</name>
            <url>http://3.7.45.122:8082/repository/maven-releases/</url>
        </repository>

    </distributionManagement>


    <!-- Build Configuration -->
    <build>

        <plugins>


            <!-- Java Compiler -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>

                <configuration>
                    <source>21</source>
                    <target>21</target>
                </configuration>

            </plugin>


            <!-- Unit Test Execution -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.5.2</version>
            </plugin>


            <!-- Spring Boot -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>

                <executions>

                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>

                </executions>

            </plugin>


        </plugins>

    </build>

</project>
